//
// Created by pikachu on 2021/5/10.
//

#ifndef QTMARKDOWNPARSER_QTMARKDOWN_GLOBAL_H
#define QTMARKDOWNPARSER_QTMARKDOWN_GLOBAL_H
#include <QtCore/qglobal.h>
#if defined(BUILD_STATIC)
#define QTMARKDOWNSHARED_EXPORT
#else
#if defined(QtMarkdown_LIBRARY)
#define QTMARKDOWNSHARED_EXPORT Q_DECL_EXPORT
#else
#define QTMARKDOWNSHARED_EXPORT Q_DECL_IMPORT
#endif
#endif

#if defined(QtWidgetMarkdownEditor_LIBRARY)
#  define QTWIDGETMARKDOWNEDITOR_EXPORT Q_DECL_EXPORT
#else
#  define QTWIDGETMARKDOWNEDITOR_EXPORT Q_DECL_IMPORT
#endif

#if defined(QtQuickMarkdownEditor_LIBRARY)
#  define QTQUICKMARKDOWNEDITOR_EXPORT Q_DECL_EXPORT
#else
#  define QTQUICKMARKDOWNEDITOR_EXPORT Q_DECL_IMPORT
#endif
#endif  // QTMARKDOWNPARSER_QTMARKDOWN_GLOBAL_H
